AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String

Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${BucketName}"
      Tags:
        - Key: "project"
          Value: "pet-etl"