AWSTemplateFormatVersion: "2010-09-09"
Description: "Resources for Compute, Database and Storage"

Parameters:
  DBPassword:
    Description: "Enter the password for the database"
    Type: "String"
    NoEcho: "true"

Resources:
  GlueScriptsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "pet-etl-glue-scripts"
      Tags:
        - Key: "project"
          Value: "pet-etl"

  LambdaCodeBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "pet-etl-lambda-code-storage"
      Tags:
        - Key: "project"
          Value: "pet-etl"

  RawDataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "pet-etl-raw-data-storage"
      Tags:
        - Key: "project"
          Value: "pet-etl"

  PetEtlDBSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      Tags:
        - Key: "project"
          Value: "pet-etl"
      GroupDescription: "Allow access to the RDS instance"
      DBSecurityGroupIngress:
        - CIDRIP: "0.0.0.0/0"

  PetEtlDBInstance:
    Type: "AWS::RDS::DBInstance"
    Description: "RDS instance for pet-etl project"
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: "db.t3.micro"
      Engine: "postgres"
      EngineVersion: "14.7"
      DBInstanceIdentifier: "PetEtlDBInstance"
      MasterUsername: "postgres"
      MasterUserPassword: !Sub "${DBPassword}"
      DBSecurityGroups:
        - !Ref "PetEtlDBSecurityGroup"
      PubliclyAccessible: "true"
      Tags:
        - Key: "project"
          Value: "pet-etl"

  MetabaseInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-053b0d53c279acc90"
      InstanceType: "t2.micro"
      KeyName: "MetabasePetIvan"
      SecurityGroupIds:
        - !Ref "MetabaseSecurityGroup"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install -y default-jdk wget
          wget https://downloads.metabase.com/v0.41.2/metabase.jar
          wget https://jdbc.postgresql.org/download/postgresql-42.2.23.jar
          echo 'export MB_JETTY_ACCEPTORS=2' >> /etc/environment
          echo 'export MB_JETTY_THREADS=50' >> /etc/environment
          echo 'export MB_DB_TYPE=postgres' >> /etc/environment
          echo 'export MB_DB_PORT=5432' >> /etc/environment
          java -jar metabase.jar &
      Tags:
        - Key: "project"
          Value: "pet-etl"

  MetabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: "22"
          ToPort: "22"
          IpProtocol: "tcp"
        - CidrIp: "0.0.0.0/0"
          FromPort: "3000"
          ToPort: "3000"
          IpProtocol: "tcp"
      Tags:
        - Key: "project"
          Value: "pet-etl"

Outputs:
  DBEndpoint:
    Description: "Endpoint for the created RDS instance"
    Value: !GetAtt "PetEtlDBInstance.Endpoint.Address"

  MetabaseURL:
    Description: "URL to access the Metabase instance"
    Value: !Sub "http://${MetabaseInstance.PublicIp}:3000"
