Parameters:
  LayerName:
    Type: String
  LayerS3Bucket:
    Type: String
  LayerS3Key:
    Type: String

Resources:
  MyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: !Ref LayerS3Bucket
        S3Key: !Ref LayerS3Key
      LayerName: !Ref LayerName